FROM  homeassistant/aarch64-hassio-supervisor

RUN ln -sf /var/run/balena-engine.sock /run/docker.sock
# RUN ln -sf /host/run/dbus /run/dbus
RUN ln -s /host/run/dbus/system_bus_socket /run/dbus/system_bus_socket
