version: '2'
volumes:
    config:
    supervisor-share:
services:
  homeassistant:
    build: homeassistant
    ports:
      - 80:8123
    privileged: true
    volumes:
      - 'config:/config'
    restart: always
    devices:
      - "/dev:/dev"
      - "/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave"
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always
  hass-configurator:
    image: "causticlab/hass-configurator-docker:arm"
    restart: always
    ports:
      - "8080:3218"
    volumes:
      - 'config:/hass-config'
    environment:
      - HC_BASEPATH=/hass-config
  hassio_supervisor:
    image: "homeassistant/aarch64-hassio-supervisor"
    container_name: hassio_supervisor
    restart: always
    privileged: true
    entrypoint: ["/bin/bash", "-c", "/scripts/start_hassio.sh"]
    security_opt:
      - seccomp:unconfined
    environment:
      - HOMEASSISTANT_REPOSITORY=homeassistant/raspberrypi4-64-homeassistant
      - SUPERVISOR_SHARE=supervisor-share
      - SUPERVISOR_NAME=hassio_supervisor
      # - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
    volumes:
      - supervisor-share:/data
      - ./scripts:/scripts
      # - /var/run/docker.sock:/var/run/docker.sock
    labels:
      io.balena.features.balena-socket: '1'
      io.balena.features.dbus: '1'
